### ISSUE TITLE
Null Pointer exception

### ISSUE THREAD

**Issue by yazeed44** [ScienJus/PixivParser#10]
Stacktrace

```
Exception in thread "Thread-3" java.lang.NullPointerException
    at java.net.URI$Parser.parse(URI.java:3042)
    at java.net.URI.<init>(URI.java:588)
    at java.net.URI.create(URI.java:850)
    at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:69)
    at com.scienjus.thread.IllustImageDownloadTask.defaultHttpGet(IllustImageDownloadTask.java:30)
    at com.scienjus.thread.IllustImageDownloadTask.run(IllustImageDownloadTask.java:37)
```

**Comment by ScienJus** [comment]
please tell me the key word or illustId, the large url maybe is null and i don't know how to handle that

**Comment by yazeed44** [comment]
``` java

if (mClient.login()){
                    final List<IllustListItem> matchedIllust = mClient.search(request.getKeywords(),request.getLimit());
                    System.out.println(matchedIllust.toString());

                    for(final IllustListItem item : matchedIllust){

                        final Illust illust = mClient.getIllust(item.getId());

                        for(final IllustImage image : illust.getImages()){
                            new Thread(createImageDownloadTask(image)).start();
                        }
                    }
                }

```

the keywords is `naruto` and the limit is `3`

**Comment by yazeed44** [comment]
All key words and limits i have entered seems to produce this exception

**Comment by yazeed44** [comment]
`matchedIllust` seems to be fine , it has values

**Comment by ScienJus** [comment]
i have a mistake that the param's name is `url_sizes` but i set `url_size`

**Comment by yazeed44** [comment]
Silly mistake :joy: , I might try it tomorrow and see what happens

Thanks

**Comment by ScienJus** [comment]
@ScienJus
