### ISSUE TITLE
Can't search for some words

### ISSUE THREAD

**Issue by yazeed44** [ScienJus/PixivParser#7]
It seems i can't search for the word `utaha` even though i could i do it on the old api

```
Exception in thread "Thread-3" java.lang.NullPointerException
    at client.PixivApiClient.search(PixivApiClient.java:350)
    at client.PixivApiClient.search(PixivApiClient.java:328)
    at GetImagesCommand$1.run(GetImagesCommand.java:54)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by ScienJus** [comment]
it's ok in the latest version.

**Comment by ScienJus** [comment]
and the pixiv search api can not be very good support in English, Sometimes you need to change the key word from English to Japanese,

**Comment by yazeed44** [comment]
``` java
public List<IllustListItem> search(String keyWord, int limit)
```

Does this method searches through tags or description ?

ps : nice profile pic :+1:

**Comment by ScienJus** [comment]
yes,tags and title.
